"""Initial migration

Revision ID: 17d1503b5b8b
Revises:
Create Date: 2025-12-16 19:13:52.397994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '17d1503b5b8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create ENUM types if they don't exist
    # Using DO block to safely create types only if they don't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE user_role AS ENUM ('ADMIN', 'PLAYER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE question_difficulty AS ENUM ('EASY', 'MEDIUM', 'HARD');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE trivia_status AS ENUM ('DRAFT', 'LOBBY', 'IN_PROGRESS', 'FINISHED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE participation_status AS ENUM ('INVITED', 'JOINED', 'READY', 'FINISHED', 'DISCONNECTED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Check if tables already exist before creating them
    # Using DO blocks to safely create tables only if they don't exist
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE users (
                id UUID NOT NULL,
                name VARCHAR NOT NULL,
                email VARCHAR NOT NULL,
                password_hash VARCHAR NOT NULL,
                role user_role NOT NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            );
            CREATE UNIQUE INDEX ix_users_email ON users (email);
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # Create questions table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE questions (
                id UUID NOT NULL,
                text VARCHAR NOT NULL,
                difficulty question_difficulty NOT NULL,
                created_by_user_id UUID,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY(created_by_user_id) REFERENCES users (id)
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # Create trivias table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE trivias (
                id UUID NOT NULL,
                title VARCHAR NOT NULL,
                description VARCHAR NOT NULL,
                topic VARCHAR,
                created_by_user_id UUID NOT NULL,
                status trivia_status NOT NULL,
                current_question_index INTEGER NOT NULL,
                question_started_at TIMESTAMP WITHOUT TIME ZONE,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                started_at TIMESTAMP WITHOUT TIME ZONE,
                finished_at TIMESTAMP WITHOUT TIME ZONE,
                PRIMARY KEY (id),
                FOREIGN KEY(created_by_user_id) REFERENCES users (id)
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # Create options table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE options (
                id UUID NOT NULL,
                question_id UUID NOT NULL,
                text VARCHAR NOT NULL,
                is_correct BOOLEAN NOT NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY(question_id) REFERENCES questions (id)
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # Create participations table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE participations (
                id UUID NOT NULL,
                trivia_id UUID NOT NULL,
                user_id UUID NOT NULL,
                status participation_status NOT NULL,
                score INTEGER NOT NULL,
                joined_at TIMESTAMP WITHOUT TIME ZONE,
                ready_at TIMESTAMP WITHOUT TIME ZONE,
                finished_at TIMESTAMP WITHOUT TIME ZONE,
                PRIMARY KEY (id),
                FOREIGN KEY(trivia_id) REFERENCES trivias (id),
                FOREIGN KEY(user_id) REFERENCES users (id),
                UNIQUE (trivia_id, user_id)
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # Create trivia_questions table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE trivia_questions (
                id UUID NOT NULL,
                trivia_id UUID NOT NULL,
                question_id UUID NOT NULL,
                position INTEGER NOT NULL,
                time_limit_seconds INTEGER NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY(question_id) REFERENCES questions (id),
                FOREIGN KEY(trivia_id) REFERENCES trivias (id),
                UNIQUE (trivia_id, position),
                UNIQUE (trivia_id, question_id)
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # Create answers table if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE answers (
                id UUID NOT NULL,
                participation_id UUID NOT NULL,
                trivia_question_id UUID NOT NULL,
                selected_option_id UUID NOT NULL,
                is_correct BOOLEAN NOT NULL,
                earned_points INTEGER NOT NULL,
                answered_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY(participation_id) REFERENCES participations (id),
                FOREIGN KEY(selected_option_id) REFERENCES options (id),
                FOREIGN KEY(trivia_question_id) REFERENCES trivia_questions (id),
                UNIQUE (participation_id, trivia_question_id)
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('trivia_questions')
    op.drop_table('participations')
    op.drop_table('options')
    op.drop_table('trivias')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

