"""add last_seen_at to participations

Revision ID: fbc42b345094
Revises: 17d1503b5b8b
Create Date: 2025-12-17 19:23:12.808304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc42b345094'
down_revision = '17d1503b5b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add column only if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE participations ADD COLUMN last_seen_at TIMESTAMP WITHOUT TIME ZONE;
        EXCEPTION
            WHEN duplicate_column THEN null;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participations', 'last_seen_at')
    # ### end Alembic commands ###

